In [3]:
import numpy as np 

Numpy arrays

In [1]:
# list 
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [4]:
np_array = np.array([1,2,3,4,5])
print (np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

Creating a one dimensional array 

In [5]:
# creating one dimensional array 

a= np.array([1,2,3,4,5])

print (a)

[1 2 3 4 5]


In [7]:
a.shape

(5,)

In [8]:
#Two dimensional array 
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
b.shape

(2, 4)

In [10]:
c= np.array([(1,2,3),(6,4,5,),(7,8,9)])
print(c)

[[1 2 3]
 [6 4 5]
 [7 8 9]]


In [11]:
c.shape

(3, 3)

In [17]:
d = np.array([(1,2,3,4),(4,5,6,7),],dtype=float)
print(d)
type(d)

[[1. 2. 3. 4.]
 [4. 5. 6. 7.]]


numpy.ndarray

Initial Placeholders in numpy array 

In [18]:
# create a numpy arrays of zeros 

x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
# create a numpy array of ones 

y  = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
#array of a particular value 

z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
